name: anatomy_crawler
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - six
  - pip:
    - Pygments==2.1.3
    - spiderpig==2.1.0
    - seaborn==0.7.1
    - beautifulsoup4==4.5.1
    - rdflib
    - more_itertools
